### PR TITLE
Update to v0.3.8

### PR DESCRIPTION
**Pull request by pavlin-policar**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pavlin-policar** [comment]
@conda-forge/core I'm a bit confused why the first job is failing. The other sub-jobs on azure pass and build successfully, but opentsne-feedstock fails. Is this an issue on my part, or is it safe to merge?

**Comment by isuruf** [comment]
You can ignore that

**Comment by isuruf** [comment]
Also see https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#forking-and-pull-requests

**Comment by pavlin-policar** [comment]
Awesome, thanks!

**Pull request merged**
